### ISSUE TITLE
No interactive select with `kc` command

### ISSUE THREAD

**Issue by aslafy-z** [Ramilito/kubesess#28]
**Describe the bug**

**To Reproduce**

1. Install with given install steps.
2. Run `kc`
3. The context list shows up as a list, the interactive panel is not interactive.

**Expected behavior**
Shows the `fzf` alternative

**Screenshots**
```
$ kc
Possible contexts are:
azure-1
azure-2
azure-3
azure-4
azure-5
azure-6
azure-7
azure-8
```

**Desktop (please complete the following information):**
 - OS: Archlinux
 - Term: Tilix, Shell: ZSH 
 - Version: 1.2.6

**Comment by Ramilito** [comment]
Oh my, you can't use arrows or fuzzy finding at all?

**Comment by aslafy-z** [comment]
I forgot to say that using `kubesess context` directly works! I have no completion for the KC command. 
Also, when using `kubesess context` and quitting with `Ctrl+C`, my prompt comes back without the cursor.

**Comment by Ramilito** [comment]
Great catch on the cursor there, dunno how I missed that since I use ctrl-c quite often! Found a fix for that and created a separate issue for it as well #31 

Regarding your other issue, I kind of feel the error should be in the [script](https://github.com/Ramilito/kubesess/blob/main/scripts/sh/kubesess.sh).

Could be that I was missing the shebang at the top that is making the script run a different interpreter.
Could you try to add ```#!/bin/bash``` at the top of the ```kubesess.sh``` file and see if that solves it.
The file should be located at: ```$HOME/.kube/kubesess```

**Comment by Ramilito** [comment]
@aslafy-z Added shebang to the latest release, it's something we should have there even if it doesn't fix your issue.

But would love it if you could try the latest release out and see if the shebang solved it.
It also has a new select plugin!

**Comment by Ramilito** [comment]
@aslafy-z  Did your issue get fixed?

**Comment by Ramilito** [comment]
Closed due to inactivity
